using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexora.Infrastructure.Persistence.Migrations;

/// <summary>
/// Creates only the five Task module tables. Existing identity/media tables are a prerequisite.
/// The database migration baseline must be reconciled before applying with EF Core.
/// </summary>
public partial class AddTaskModule : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE analysis_tasks (
                id uuid PRIMARY KEY,
                task_number bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_id uuid NOT NULL,
                analysis_type varchar(100) NOT NULL,
                status varchar(30) NOT NULL,
                priority integer NOT NULL,
                request_payload jsonb NULL,
                idempotency_key varchar(200) NULL,
                created_at timestamptz NOT NULL,
                queued_at timestamptz NULL,
                started_at timestamptz NULL,
                completed_at timestamptz NULL,
                cancel_requested_at timestamptz NULL,
                updated_at timestamptz NOT NULL,
                CONSTRAINT fk_analysis_tasks_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT,
                CONSTRAINT ck_analysis_tasks_status CHECK (status IN ('created','queued','processing','succeeded','failed','cancel_requested','cancelled')),
                CONSTRAINT ck_analysis_tasks_priority CHECK (priority BETWEEN -100 AND 100),
                CONSTRAINT ck_analysis_tasks_type CHECK (length(btrim(analysis_type)) > 0)
            );
            CREATE UNIQUE INDEX ux_analysis_tasks_number ON analysis_tasks(task_number);
            CREATE UNIQUE INDEX ux_analysis_tasks_owner_idempotency ON analysis_tasks(owner_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
            CREATE INDEX ix_analysis_tasks_owner_created ON analysis_tasks(owner_id, created_at DESC);
            CREATE INDEX ix_analysis_tasks_status_created ON analysis_tasks(status, created_at);

            CREATE TABLE analysis_task_attempts (
                id uuid PRIMARY KEY,
                task_id uuid NOT NULL,
                attempt_number integer NOT NULL,
                status varchar(30) NOT NULL,
                worker_id varchar(200) NULL,
                started_at timestamptz NOT NULL,
                completed_at timestamptz NULL,
                heartbeat_at timestamptz NULL,
                error_code varchar(100) NULL,
                error_message text NULL,
                processing_duration_ms bigint NULL,
                created_at timestamptz NOT NULL,
                CONSTRAINT fk_analysis_task_attempts_task FOREIGN KEY (task_id) REFERENCES analysis_tasks(id) ON DELETE CASCADE,
                CONSTRAINT ck_analysis_task_attempts_status CHECK (status IN ('running','succeeded','failed','cancelled')),
                CONSTRAINT ck_analysis_task_attempts_number CHECK (attempt_number > 0),
                CONSTRAINT ck_analysis_task_attempts_duration CHECK (processing_duration_ms IS NULL OR processing_duration_ms >= 0)
            );
            CREATE UNIQUE INDEX ux_analysis_task_attempts_number ON analysis_task_attempts(task_id, attempt_number);

            CREATE TABLE analysis_results (
                id uuid PRIMARY KEY,
                task_id uuid NOT NULL,
                result_type varchar(100) NOT NULL,
                schema_version varchar(20) NOT NULL,
                result_payload jsonb NOT NULL,
                confidence_score numeric(5,4) NULL,
                is_current boolean NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                CONSTRAINT fk_analysis_results_task FOREIGN KEY (task_id) REFERENCES analysis_tasks(id) ON DELETE RESTRICT,
                CONSTRAINT ck_analysis_results_score CHECK (confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1)
            );
            CREATE INDEX ix_analysis_results_task_type ON analysis_results(task_id, result_type);
            CREATE UNIQUE INDEX ux_analysis_results_current_type ON analysis_results(task_id, result_type) WHERE is_current = true;

            CREATE TABLE generated_artifacts (
                id uuid PRIMARY KEY,
                task_id uuid NOT NULL,
                result_id uuid NULL,
                artifact_type varchar(100) NOT NULL,
                file_name varchar(255) NOT NULL,
                storage_provider varchar(30) NOT NULL,
                storage_bucket varchar(255) NULL,
                storage_key text NOT NULL,
                content_type varchar(150) NULL,
                size_bytes bigint NULL,
                content_hash varchar(64) NULL,
                status varchar(30) NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                CONSTRAINT fk_generated_artifacts_task FOREIGN KEY (task_id) REFERENCES analysis_tasks(id) ON DELETE RESTRICT,
                CONSTRAINT fk_generated_artifacts_result FOREIGN KEY (result_id) REFERENCES analysis_results(id) ON DELETE RESTRICT,
                CONSTRAINT ck_generated_artifacts_provider CHECK (storage_provider IN ('local','swift','s3')),
                CONSTRAINT ck_generated_artifacts_status CHECK (status IN ('generating','ready','failed','deleted')),
                CONSTRAINT ck_generated_artifacts_storage CHECK ((storage_provider = 'local' AND storage_bucket IS NULL) OR (storage_provider IN ('swift','s3') AND storage_bucket IS NOT NULL AND length(btrim(storage_bucket)) > 0)),
                CONSTRAINT ck_generated_artifacts_key CHECK (length(btrim(storage_key)) > 0),
                CONSTRAINT ck_generated_artifacts_size CHECK (size_bytes IS NULL OR size_bytes >= 0),
                CONSTRAINT ck_generated_artifacts_hash CHECK (content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$')
            );
            CREATE INDEX ix_generated_artifacts_task_created ON generated_artifacts(task_id, created_at);
            CREATE INDEX ix_generated_artifacts_result ON generated_artifacts(result_id);
            CREATE UNIQUE INDEX ux_generated_artifacts_local_storage ON generated_artifacts(storage_key) WHERE storage_provider = 'local';
            CREATE UNIQUE INDEX ux_generated_artifacts_cloud_storage ON generated_artifacts(storage_provider, storage_bucket, storage_key) WHERE storage_provider IN ('swift','s3');

            CREATE TABLE task_inputs (
                id uuid PRIMARY KEY,
                task_id uuid NOT NULL,
                input_type varchar(30) NOT NULL,
                input_role varchar(100) NOT NULL,
                asset_file_id uuid NULL,
                artifact_id uuid NULL,
                created_at timestamptz NOT NULL,
                CONSTRAINT fk_task_inputs_task FOREIGN KEY (task_id) REFERENCES analysis_tasks(id) ON DELETE CASCADE,
                CONSTRAINT fk_task_inputs_asset_file FOREIGN KEY (asset_file_id) REFERENCES asset_files(id) ON DELETE RESTRICT,
                CONSTRAINT fk_task_inputs_artifact FOREIGN KEY (artifact_id) REFERENCES generated_artifacts(id) ON DELETE RESTRICT,
                CONSTRAINT ck_task_inputs_target CHECK ((input_type = 'asset_file' AND asset_file_id IS NOT NULL AND artifact_id IS NULL) OR (input_type = 'artifact' AND artifact_id IS NOT NULL AND asset_file_id IS NULL))
            );
            CREATE INDEX ix_task_inputs_task_created ON task_inputs(task_id, created_at);
            CREATE INDEX ix_task_inputs_asset_file ON task_inputs(asset_file_id);
            CREATE INDEX ix_task_inputs_artifact ON task_inputs(artifact_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        throw new NotSupportedException("Task module rollback requires a reviewed data and artifact retention plan.");
}
