// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexora.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NexoraDbContext))]
    [Migration("20260726053239_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_task_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResultData")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_data");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_type");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTaskId");

                    b.ToTable("analysis_result", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisData")
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("analysis_task", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.AnalysisTask", "AnalysisTask")
                        .WithMany("Results")
                        .HasForeignKey("AnalysisTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisTask");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTask", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
