// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexora.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NexoraDbContext))]
    partial class NexoraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<JsonDocument>("ResultPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_payload");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result_type");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "ResultType")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_results_current_type")
                        .HasFilter("is_current = true");

                    b.ToTable("analysis_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_results_score", "confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("analysis_type");

                    b.Property<DateTime?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<JsonDocument>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long>("TaskNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("task_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaskNumber"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaskNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_tasks_number");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_analysis_tasks_owner_created");

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_tasks_owner_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_analysis_tasks_status_created");

                    b.ToTable("analysis_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_tasks_priority", "priority BETWEEN -100 AND 100");

                            t.HasCheckConstraint("ck_analysis_tasks_status", "status IN ('created','queued','processing','succeeded','failed','cancel_requested','cancelled')");

                            t.HasCheckConstraint("ck_analysis_tasks_type", "length(btrim(analysis_type)) > 0");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTaskAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<long?>("ProcessingDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_duration_ms");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_task_attempts_number");

                    b.ToTable("analysis_task_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_task_attempts_duration", "processing_duration_ms IS NULL OR processing_duration_ms >= 0");

                            t.HasCheckConstraint("ck_analysis_task_attempts_number", "attempt_number > 0");

                            t.HasCheckConstraint("ck_analysis_task_attempts_status", "status IN ('running','succeeded','failed','cancelled')");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AssetFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("file_role");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("StorageBucket")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("local")
                        .HasColumnName("storage_provider");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("asset_files_pkey");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_asset_files_original")
                        .HasFilter("file_role = 'original' AND deleted_at IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_asset_files_cleanup")
                        .HasFilter("status = 'deleting'");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_asset_files_local_storage")
                        .HasFilter("storage_provider = 'local'");

                    b.HasIndex("AssetId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_asset_files_asset")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("StorageProvider", "StorageBucket", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_asset_files_cloud_storage")
                        .HasFilter("storage_provider IN ('swift', 's3')");

                    b.ToTable("asset_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_asset_files_deleted", "status <> 'deleted' OR deleted_at IS NOT NULL");

                            t.HasCheckConstraint("ck_asset_files_hash", "content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_asset_files_key", "length(btrim(storage_key)) > 0");

                            t.HasCheckConstraint("ck_asset_files_name", "length(btrim(original_name)) > 0");

                            t.HasCheckConstraint("ck_asset_files_provider", "storage_provider IN ('local', 'swift', 's3')");

                            t.HasCheckConstraint("ck_asset_files_role", "file_role IN ('original', 'subtitle', 'reference_script', 'attachment')");

                            t.HasCheckConstraint("ck_asset_files_size", "size_bytes IS NULL OR size_bytes >= 0");

                            t.HasCheckConstraint("ck_asset_files_status", "status IN ('pending', 'uploading', 'ready', 'failed', 'deleting', 'deleted')");

                            t.HasCheckConstraint("ck_asset_files_storage", "(storage_provider = 'local' AND storage_bucket IS NULL) OR (storage_provider IN ('swift', 's3') AND storage_bucket IS NOT NULL AND length(btrim(storage_bucket)) > 0)");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.GeneratedArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("artifact_type");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StorageBucket")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("storage_provider");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResultId")
                        .HasDatabaseName("ix_generated_artifacts_result");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_generated_artifacts_local_storage")
                        .HasFilter("storage_provider = 'local'");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_generated_artifacts_task_created");

                    b.HasIndex("StorageProvider", "StorageBucket", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_generated_artifacts_cloud_storage")
                        .HasFilter("storage_provider IN ('swift','s3')");

                    b.ToTable("generated_artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_generated_artifacts_hash", "content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_generated_artifacts_key", "length(btrim(storage_key)) > 0");

                            t.HasCheckConstraint("ck_generated_artifacts_provider", "storage_provider IN ('local','swift','s3')");

                            t.HasCheckConstraint("ck_generated_artifacts_size", "size_bytes IS NULL OR size_bytes >= 0");

                            t.HasCheckConstraint("ck_generated_artifacts_status", "status IN ('generating','ready','failed','deleted')");

                            t.HasCheckConstraint("ck_generated_artifacts_storage", "(storage_provider = 'local' AND storage_bucket IS NULL) OR (storage_provider IN ('swift','s3') AND storage_bucket IS NOT NULL AND length(btrim(storage_bucket)) > 0)");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("video")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("assets_pkey");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_assets_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_assets_owner_created")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_assets_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_assets_status", "status IN ('active', 'archived')");

                            t.HasCheckConstraint("ck_assets_type", "asset_type IN ('video', 'audio', 'image', 'document')");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.MediaMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssetFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_file_id");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("integer")
                        .HasColumnName("audio_channels");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audio_codec");

                    b.Property<int?>("AudioSampleRate")
                        .HasColumnType("integer")
                        .HasColumnName("audio_sample_rate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DurationSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FormatName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("format_name");

                    b.Property<int?>("FpsDen")
                        .HasColumnType("integer")
                        .HasColumnName("fps_den");

                    b.Property<int?>("FpsNum")
                        .HasColumnType("integer")
                        .HasColumnName("fps_num");

                    b.Property<long?>("FrameCount")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_count");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool?>("IsVariableFps")
                        .HasColumnType("boolean")
                        .HasColumnName("is_variable_fps");

                    b.Property<JsonDocument>("ProbeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("probe_json");

                    b.Property<DateTime?>("ProbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("probed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("video_codec");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("media_metadata_pkey");

                    b.HasIndex("AssetFileId")
                        .IsUnique()
                        .HasDatabaseName("uq_media_metadata_file");

                    b.ToTable("media_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_metadata_audio", "(audio_sample_rate IS NULL OR audio_sample_rate > 0) AND (audio_channels IS NULL OR audio_channels > 0)");

                            t.HasCheckConstraint("ck_media_metadata_dimensions", "(width IS NULL OR width > 0) AND (height IS NULL OR height > 0)");

                            t.HasCheckConstraint("ck_media_metadata_duration", "duration_seconds IS NULL OR duration_seconds >= 0");

                            t.HasCheckConstraint("ck_media_metadata_fps", "(fps_num IS NULL AND fps_den IS NULL) OR (fps_num > 0 AND fps_den > 0)");

                            t.HasCheckConstraint("ck_media_metadata_frame_count", "frame_count IS NULL OR frame_count >= 0");

                            t.HasCheckConstraint("ck_media_metadata_probe_json", "probe_json IS NULL OR jsonb_typeof(probe_json) = 'object'");

                            t.HasCheckConstraint("ck_media_metadata_status", "status IN ('pending', 'processing', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("Nexora.Domain.Entities.TaskInput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<Guid?>("AssetFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_file_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("input_role");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("input_type");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_task_inputs_artifact");

                    b.HasIndex("AssetFileId")
                        .HasDatabaseName("ix_task_inputs_asset_file");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_task_inputs_task_created");

                    b.ToTable("task_inputs", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_inputs_target", "(input_type = 'asset_file' AND asset_file_id IS NOT NULL AND artifact_id IS NULL) OR (input_type = 'artifact' AND artifact_id IS NOT NULL AND asset_file_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Nexora.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.AnalysisTask", "Task")
                        .WithMany("Results")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTask", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTaskAttempt", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.AnalysisTask", "Task")
                        .WithMany("Attempts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AssetFile", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.MediaAsset", "Asset")
                        .WithMany("Files")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_files_asset");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.GeneratedArtifact", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.AnalysisResult", "Result")
                        .WithMany("Artifacts")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexora.Domain.Entities.AnalysisTask", "Task")
                        .WithMany("Artifacts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Result");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("Nexora.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_owner");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.MediaMetadata", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.AssetFile", "AssetFile")
                        .WithOne("Metadata")
                        .HasForeignKey("Nexora.Domain.Entities.MediaMetadata", "AssetFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_metadata_file");

                    b.Navigation("AssetFile");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.TaskInput", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.GeneratedArtifact", "Artifact")
                        .WithMany("UsedByInputs")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexora.Domain.Entities.AssetFile", "AssetFile")
                        .WithMany()
                        .HasForeignKey("AssetFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexora.Domain.Entities.AnalysisTask", "Task")
                        .WithMany("Inputs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("AssetFile");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisResult", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AnalysisTask", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Attempts");

                    b.Navigation("Inputs");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.AssetFile", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.GeneratedArtifact", b =>
                {
                    b.Navigation("UsedByInputs");
                });

            modelBuilder.Entity("Nexora.Domain.Entities.MediaAsset", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
